[package]
name = "peck-exif"
version = "1.0.1"
description = "Exif reader"
license = "MIT"
edition = "2021"
repository = "https://github.com/alexipeck/exif"
categories = ["filesystem, parsing"]
authors = ["Alexi Peck"]
exclude = ["/target"]

[lib]
doctest = false

[dependencies]
